#!/bin/sh

cd
sudo rm -r client
git clone git@github.com:Neurobica-LLC/neurobica-app.git client
cd client
npm install
npm run build
cd server
npm install
pm2 stop all
pm2 start npm -- start "asd"
cd ..
sudo rm -r /var/www/html
sudo mkdir /var/www/html
sudo cp -r build/* /var/www/html/
sudo systemctl restart nginx

